
CREATE TABLE IF NOT EXISTS products
(
    product_id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    product_name VARCHAR(255) NOT NULL,
    product_description VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE IF NOT EXISTS reviews
(
    reviews_id INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    comment VARCHAR(255) NOT NULL,
    rate INTEGER NOT NULL,
    product_id INTEGER NOT NULL REFERENCES products
);